# Try to write your query here
{
  courses {
    title
    bio
    price
    disCount
    image
    imageURL
    tags
    teacher {
      first_name
    }
    category{
      title
    }
    chapters {
      title
      text
      episodes {
        title
        time
        type
        videoAddress
        videoUrl
      }
    }
     comments {
    comment
    show
    user{
      first_name
    }
    openToComment
    answers{
      comment
      user{
        first_name
      }
      show
    }
  }
  }
}