query getCourses($categoryId: String) {
  alias: courses(category: $categoryId) {
    ...courseFields
  }
}

fragment courseFields on courseType {
  title
  image
  imageURL
  tags
  teacher {
    first_name
  }
  category {
    title
  }
  chapters {
    text
    episodes {
      title
      time
      type
      videoAddress
      videoUrl
    }
  }
  comments {
    comment
    _id
    show
    user {
      first_name
    }
    openToComment
    answers {
      _id
      comment
      user {
        first_name
      }
      show
    }
  }
}
